1
yurec26/pet_shelter pull request #1
Opened 2024-10-29 12:10 UTC by yurec26

2024-11-04 11:34 UTC, pas-zhukov requested changes

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/constants/AviaryConstants.java
> +    public static final int ADOPT_AVIARY_NUM = 9999;
Зачем тебе складывать усыновлённых животных в авиари, если ты можешь просто сделать для животного это поле `null`

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Animal.java
> +    public Animal() {
Не вижу, где бы использовался этот конструктор

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Animal.java
> +    private Set<String> vaccList = new HashSet<>();
можно сделать поля финальными, идея зачастую корректно подсказывает. если ты поле один раз только присваиваешь (ссылку), то можно его сделать финальным

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    public Aviary() {
То же что и в животном

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    private List<Integer> animalList;
Тут тоже можно сделать поле финальным. У тебя оно не финальное, т.к. есть сеттер, но фактически ты этим сеттером не пользуешься, у тебя один лист на объект с рождения и до смерти

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Owner.java
> +    public Owner() {
То же самое. Зачем?

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    private List<Integer> animalList;
Ошибся, у тебя оно не финальное, т.к. в конструкторе идет повторное присваивание. Нужно в конструкторе явно присваивать

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    private List<Integer> animalList;
Я ошибся ещё раз, у тебя оно не финальное, т.к. в конструкторе без параметров это поле не инициализируется

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/repository/AnimalRepository.java
> +    private final List<Animal> animalList = new CopyOnWriteArrayList<>();
Зачем `CopyOnWriteArrayList`?

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/util/MaxIDCounterUtil.java
> +    public static int countMaxID(List<Animal> storage) {
Этот метод можно было бы в `IdGenerator` поместить вполне

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/util/IOUtil.java
> +    private static final String AVIARIES_REPO_FILE = "backend/src/main/resources/aviaries.json";
Пути должны быть в файле свойств по типу `app.properties`. Поскольку без спринга будет несколько заморочно их парсить, то на текущем этапе ок

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/util/IOUtil.java
> +    public static <T> void updateRepoFileAnimal(List<T> list) throws IOException {
Зачем здесь нужна типизация? Можно же `Animal` указать. В назывании то указано

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/util/IOUtil.java
> +    public static <T> void updateRepoFileAnimal(List<T> list) throws IOException {
То же самое и в других методах

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/util/JsonUtil.java
> +    public static <T> List<T> jsonToMap(String path, Class<T> clazz) throws IOException {
Мб всё-таки toList?

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/repository/AnimalRepository.java
> +    public AnimalRepository add(Animal animal) {
Такой метод должен быть изначально определён в абстрактной сущности, т.к. любой репозиторий по сути должен поддерживать CRUD

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/repository/ShelterRepository.java
> +
Не вижу эту штуку интерфейсом, а вот абстрактным классом она может быть запросто - сразу сократит кучу кода. Например,
```java
public abstract class ShelterRepository<T extends Entity> {

     List<T> entities = new ArrayList<>();

     public T getById(int id) {
         return entities.stream().filter(s -> s.getId() == id).findAny().orElse(null);
     }

     public ShelterRepository<T> update(T entity) {
         entities.set(entities.indexOf(entity), entity);
         return this;
     }

     public List<T> getAll() {
         return entities;
     }

    abstract ShelterRepository<T> loadFromRepo() throws IOException;

    abstract void updateRepoFile() throws IOException;
}
```

2024-11-04 11:34 UTC, pas-zhukov commented on backend/src/main/java/org/example/backend/repository/ShelterRepository.java
> +
`Entity` в данном случае, это интерфейс с единственным метдом `getId()`, который имплементируют твои классы сущностей

2024-11-07 12:32 UTC, yurec26 commented on backend/src/main/java/org/example/backend/constants/AviaryConstants.java
> +    public static final int ADOPT_AVIARY_NUM = 9999;
Сделал

2024-11-07 12:34 UTC, yurec26 commented on backend/src/main/java/org/example/backend/entity/Animal.java
> +    public Animal() {
Jackson десериализует объекты с помощью пустого конструктора.

_"Jackson использует конструктор без параметров для того, чтобы создать объект перед тем, как начать присваивать значения полям объекта."_

2024-11-07 12:34 UTC, yurec26 commented on backend/src/main/java/org/example/backend/entity/Animal.java
> +    private Set<String> vaccList = new HashSet<>();
Сделал

2024-11-07 12:35 UTC, yurec26 commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    public Aviary() {
То же что и в животном)

2024-11-07 12:37 UTC, yurec26 commented on backend/src/main/java/org/example/backend/entity/Aviary.java
> +    private List<Integer> animalList;
Оставил не финальным

2024-11-07 12:37 UTC, yurec26 commented on backend/src/main/java/org/example/backend/entity/Owner.java
> +    public Owner() {
Ответ уже дал выше

2024-11-07 12:38 UTC, yurec26 commented on backend/src/main/java/org/example/backend/repository/AnimalRepository.java
> +    private final List<Animal> animalList = new CopyOnWriteArrayList<>();
Испрапвил

2024-11-07 12:38 UTC, yurec26 commented on backend/src/main/java/org/example/backend/util/MaxIDCounterUtil.java
> +    public static int countMaxID(List<Animal> storage) {
Поместил

2024-11-07 12:38 UTC, yurec26 commented on backend/src/main/java/org/example/backend/util/IOUtil.java
> +    private static final String AVIARIES_REPO_FILE = "backend/src/main/resources/aviaries.json";
Оставил как есть, информацию принял

2024-11-07 12:38 UTC, yurec26 commented on backend/src/main/java/org/example/backend/util/IOUtil.java
> +    public static <T> void updateRepoFileAnimal(List<T> list) throws IOException {
Убрал типизацию

2024-11-07 12:39 UTC, yurec26 commented on backend/src/main/java/org/example/backend/util/JsonUtil.java
> +    public static <T> List<T> jsonToMap(String path, Class<T> clazz) throws IOException {
может быть) поправил

2024-11-07 12:39 UTC, yurec26 commented on backend/src/main/java/org/example/backend/repository/AnimalRepository.java
> +    public AnimalRepository add(Animal animal) {
Сделал

2024-11-07 12:39 UTC, yurec26 commented on backend/src/main/java/org/example/backend/repository/ShelterRepository.java
> +
Сделал

2024-11-07 19:21 UTC, merged